/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Bridge {
  export type RequestInfoStruct = {
    id: BigNumberish;
    requestBy: AddressLike;
    fromChainId: BigNumberish;
    fromValue: BigNumberish;
    toChainId: BigNumberish;
    toValue: BigNumberish;
    status: BigNumberish;
    statusDecidedBy: AddressLike;
    exchangedAt: BigNumberish;
  };

  export type RequestInfoStructOutput = [
    id: bigint,
    requestBy: string,
    fromChainId: bigint,
    fromValue: bigint,
    toChainId: bigint,
    toValue: bigint,
    status: bigint,
    statusDecidedBy: string,
    exchangedAt: bigint
  ] & {
    id: bigint;
    requestBy: string;
    fromChainId: bigint;
    fromValue: bigint;
    toChainId: bigint;
    toValue: bigint;
    status: bigint;
    statusDecidedBy: string;
    exchangedAt: bigint;
  };
}

export interface BridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addBalance"
      | "addChain"
      | "cancelRequest"
      | "chainList"
      | "owner"
      | "removeChain"
      | "renounceOwnership"
      | "request"
      | "requestList"
      | "setRequest"
      | "setWhiteList"
      | "transferOwnership"
      | "triggerPayout"
      | "whiteList"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddBalance"
      | "ChainListUpdated"
      | "OwnershipTransferred"
      | "Requested"
      | "SetRequested"
      | "TriggerPayouted"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "chainList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "request",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhiteList",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerPayout",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteList",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addChain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chainList", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "request", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whiteList", data: BytesLike): Result;
}

export namespace AddBalanceEvent {
  export type InputTuple = [_address: AddressLike, value: BigNumberish];
  export type OutputTuple = [_address: string, value: bigint];
  export interface OutputObject {
    _address: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChainListUpdatedEvent {
  export type InputTuple = [chainId: BigNumberish, status: boolean];
  export type OutputTuple = [chainId: bigint, status: boolean];
  export interface OutputObject {
    chainId: bigint;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestedEvent {
  export type InputTuple = [
    requestedBy: AddressLike,
    request: Bridge.RequestInfoStruct
  ];
  export type OutputTuple = [
    requestedBy: string,
    request: Bridge.RequestInfoStructOutput
  ];
  export interface OutputObject {
    requestedBy: string;
    request: Bridge.RequestInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requestStatus: BigNumberish,
    requestedBy: AddressLike
  ];
  export type OutputTuple = [
    requestId: bigint,
    requestStatus: bigint,
    requestedBy: string
  ];
  export interface OutputObject {
    requestId: bigint;
    requestStatus: bigint;
    requestedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerPayoutedEvent {
  export type InputTuple = [_address: AddressLike, value: BigNumberish];
  export type OutputTuple = [_address: string, value: bigint];
  export interface OutputObject {
    _address: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [_address: AddressLike, status: boolean];
  export type OutputTuple = [_address: string, status: boolean];
  export interface OutputObject {
    _address: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bridge extends BaseContract {
  connect(runner?: ContractRunner | null): Bridge;
  waitForDeployment(): Promise<this>;

  interface: BridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addBalance: TypedContractMethod<[], [void], "payable">;

  addChain: TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;

  cancelRequest: TypedContractMethod<
    [requestId: BigNumberish],
    [void],
    "nonpayable"
  >;

  chainList: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { id: bigint; active: boolean }],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  request: TypedContractMethod<
    [toChainId: BigNumberish, _value: BigNumberish],
    [void],
    "payable"
  >;

  requestList: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        requestBy: string;
        fromChainId: bigint;
        fromValue: bigint;
        toChainId: bigint;
        toValue: bigint;
        status: bigint;
        statusDecidedBy: string;
        exchangedAt: bigint;
      }
    ],
    "view"
  >;

  setRequest: TypedContractMethod<
    [requestId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWhiteList: TypedContractMethod<
    [_address: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerPayout: TypedContractMethod<
    [_address: AddressLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;

  whiteList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addBalance"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "addChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelRequest"
  ): TypedContractMethod<[requestId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "chainList"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, boolean] & { id: bigint; active: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "request"
  ): TypedContractMethod<
    [toChainId: BigNumberish, _value: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "requestList"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        string,
        bigint
      ] & {
        id: bigint;
        requestBy: string;
        fromChainId: bigint;
        fromValue: bigint;
        toChainId: bigint;
        toValue: bigint;
        status: bigint;
        statusDecidedBy: string;
        exchangedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWhiteList"
  ): TypedContractMethod<
    [_address: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerPayout"
  ): TypedContractMethod<
    [_address: AddressLike, _value: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whiteList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "AddBalance"
  ): TypedContractEvent<
    AddBalanceEvent.InputTuple,
    AddBalanceEvent.OutputTuple,
    AddBalanceEvent.OutputObject
  >;
  getEvent(
    key: "ChainListUpdated"
  ): TypedContractEvent<
    ChainListUpdatedEvent.InputTuple,
    ChainListUpdatedEvent.OutputTuple,
    ChainListUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Requested"
  ): TypedContractEvent<
    RequestedEvent.InputTuple,
    RequestedEvent.OutputTuple,
    RequestedEvent.OutputObject
  >;
  getEvent(
    key: "SetRequested"
  ): TypedContractEvent<
    SetRequestedEvent.InputTuple,
    SetRequestedEvent.OutputTuple,
    SetRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerPayouted"
  ): TypedContractEvent<
    TriggerPayoutedEvent.InputTuple,
    TriggerPayoutedEvent.OutputTuple,
    TriggerPayoutedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "AddBalance(address,uint256)": TypedContractEvent<
      AddBalanceEvent.InputTuple,
      AddBalanceEvent.OutputTuple,
      AddBalanceEvent.OutputObject
    >;
    AddBalance: TypedContractEvent<
      AddBalanceEvent.InputTuple,
      AddBalanceEvent.OutputTuple,
      AddBalanceEvent.OutputObject
    >;

    "ChainListUpdated(uint256,bool)": TypedContractEvent<
      ChainListUpdatedEvent.InputTuple,
      ChainListUpdatedEvent.OutputTuple,
      ChainListUpdatedEvent.OutputObject
    >;
    ChainListUpdated: TypedContractEvent<
      ChainListUpdatedEvent.InputTuple,
      ChainListUpdatedEvent.OutputTuple,
      ChainListUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Requested(address,tuple)": TypedContractEvent<
      RequestedEvent.InputTuple,
      RequestedEvent.OutputTuple,
      RequestedEvent.OutputObject
    >;
    Requested: TypedContractEvent<
      RequestedEvent.InputTuple,
      RequestedEvent.OutputTuple,
      RequestedEvent.OutputObject
    >;

    "SetRequested(uint256,uint8,address)": TypedContractEvent<
      SetRequestedEvent.InputTuple,
      SetRequestedEvent.OutputTuple,
      SetRequestedEvent.OutputObject
    >;
    SetRequested: TypedContractEvent<
      SetRequestedEvent.InputTuple,
      SetRequestedEvent.OutputTuple,
      SetRequestedEvent.OutputObject
    >;

    "TriggerPayouted(address,uint256)": TypedContractEvent<
      TriggerPayoutedEvent.InputTuple,
      TriggerPayoutedEvent.OutputTuple,
      TriggerPayoutedEvent.OutputObject
    >;
    TriggerPayouted: TypedContractEvent<
      TriggerPayoutedEvent.InputTuple,
      TriggerPayoutedEvent.OutputTuple,
      TriggerPayoutedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
