/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Bridge {
  export type RequestInfoStruct = {
    id: BigNumberish;
    requestBy: AddressLike;
    fromChainId: BigNumberish;
    fromValue: BigNumberish;
    toChainId: BigNumberish;
    toValue: BigNumberish;
    status: BigNumberish;
  };

  export type RequestInfoStructOutput = [
    id: bigint,
    requestBy: string,
    fromChainId: bigint,
    fromValue: bigint,
    toChainId: bigint,
    toValue: bigint,
    status: bigint
  ] & {
    id: bigint;
    requestBy: string;
    fromChainId: bigint;
    fromValue: bigint;
    toChainId: bigint;
    toValue: bigint;
    status: bigint;
  };
}

export interface BridgeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "owner"
      | "payoutList"
      | "renounceOwnership"
      | "request"
      | "requestIdCount"
      | "requestList"
      | "requestMaximumValue"
      | "requestMinimumValue"
      | "setMaximumValue"
      | "setMinimumValue"
      | "setRequest"
      | "setWhiteList"
      | "transferOwnership"
      | "triggerPayout"
      | "whiteList"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Requested"
      | "SetRequested"
      | "TriggerPayouted"
      | "WhitelistUpdated"
      | "setValueRange"
  ): EventFragment;

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "payoutList",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "request",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestIdCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMaximumValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestMinimumValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMaximumValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinimumValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRequest",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhiteList",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "triggerPayout",
    values: [BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "whiteList",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payoutList", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "request", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestIdCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMaximumValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMinimumValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaximumValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinimumValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRequest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "triggerPayout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whiteList", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestedEvent {
  export type InputTuple = [
    requestAddress: AddressLike,
    request: Bridge.RequestInfoStruct
  ];
  export type OutputTuple = [
    requestAddress: string,
    request: Bridge.RequestInfoStructOutput
  ];
  export interface OutputObject {
    requestAddress: string;
    request: Bridge.RequestInfoStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetRequestedEvent {
  export type InputTuple = [
    requestId: BigNumberish,
    requestStatus: BigNumberish
  ];
  export type OutputTuple = [requestId: bigint, requestStatus: bigint];
  export interface OutputObject {
    requestId: bigint;
    requestStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TriggerPayoutedEvent {
  export type InputTuple = [_address: AddressLike, value: BigNumberish];
  export type OutputTuple = [_address: string, value: bigint];
  export interface OutputObject {
    _address: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [_address: AddressLike, status: boolean];
  export type OutputTuple = [_address: string, status: boolean];
  export interface OutputObject {
    _address: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace setValueRangeEvent {
  export type InputTuple = [valueRange: BigNumberish, value: BigNumberish];
  export type OutputTuple = [valueRange: bigint, value: bigint];
  export interface OutputObject {
    valueRange: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Bridge extends BaseContract {
  connect(runner?: ContractRunner | null): Bridge;
  waitForDeployment(): Promise<this>;

  interface: BridgeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  owner: TypedContractMethod<[], [string], "view">;

  payoutList: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  request: TypedContractMethod<[toChainId: BigNumberish], [void], "payable">;

  requestIdCount: TypedContractMethod<[], [bigint], "view">;

  requestList: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        requestBy: string;
        fromChainId: bigint;
        fromValue: bigint;
        toChainId: bigint;
        toValue: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  requestMaximumValue: TypedContractMethod<[], [bigint], "view">;

  requestMinimumValue: TypedContractMethod<[], [bigint], "view">;

  setMaximumValue: TypedContractMethod<
    [max: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinimumValue: TypedContractMethod<
    [min: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRequest: TypedContractMethod<
    [requestId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWhiteList: TypedContractMethod<
    [_address: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  triggerPayout: TypedContractMethod<
    [
      fromChainId: BigNumberish,
      requestId: BigNumberish,
      _address: AddressLike,
      _value: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  whiteList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "payoutList"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "request"
  ): TypedContractMethod<[toChainId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "requestIdCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestList"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, bigint, bigint] & {
        id: bigint;
        requestBy: string;
        fromChainId: bigint;
        fromValue: bigint;
        toChainId: bigint;
        toValue: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "requestMaximumValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestMinimumValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMaximumValue"
  ): TypedContractMethod<[max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinimumValue"
  ): TypedContractMethod<[min: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRequest"
  ): TypedContractMethod<
    [requestId: BigNumberish, status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWhiteList"
  ): TypedContractMethod<
    [_address: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "triggerPayout"
  ): TypedContractMethod<
    [
      fromChainId: BigNumberish,
      requestId: BigNumberish,
      _address: AddressLike,
      _value: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whiteList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Requested"
  ): TypedContractEvent<
    RequestedEvent.InputTuple,
    RequestedEvent.OutputTuple,
    RequestedEvent.OutputObject
  >;
  getEvent(
    key: "SetRequested"
  ): TypedContractEvent<
    SetRequestedEvent.InputTuple,
    SetRequestedEvent.OutputTuple,
    SetRequestedEvent.OutputObject
  >;
  getEvent(
    key: "TriggerPayouted"
  ): TypedContractEvent<
    TriggerPayoutedEvent.InputTuple,
    TriggerPayoutedEvent.OutputTuple,
    TriggerPayoutedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "setValueRange"
  ): TypedContractEvent<
    setValueRangeEvent.InputTuple,
    setValueRangeEvent.OutputTuple,
    setValueRangeEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Requested(address,tuple)": TypedContractEvent<
      RequestedEvent.InputTuple,
      RequestedEvent.OutputTuple,
      RequestedEvent.OutputObject
    >;
    Requested: TypedContractEvent<
      RequestedEvent.InputTuple,
      RequestedEvent.OutputTuple,
      RequestedEvent.OutputObject
    >;

    "SetRequested(uint256,uint8)": TypedContractEvent<
      SetRequestedEvent.InputTuple,
      SetRequestedEvent.OutputTuple,
      SetRequestedEvent.OutputObject
    >;
    SetRequested: TypedContractEvent<
      SetRequestedEvent.InputTuple,
      SetRequestedEvent.OutputTuple,
      SetRequestedEvent.OutputObject
    >;

    "TriggerPayouted(address,uint256)": TypedContractEvent<
      TriggerPayoutedEvent.InputTuple,
      TriggerPayoutedEvent.OutputTuple,
      TriggerPayoutedEvent.OutputObject
    >;
    TriggerPayouted: TypedContractEvent<
      TriggerPayoutedEvent.InputTuple,
      TriggerPayoutedEvent.OutputTuple,
      TriggerPayoutedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;

    "setValueRange(uint8,uint256)": TypedContractEvent<
      setValueRangeEvent.InputTuple,
      setValueRangeEvent.OutputTuple,
      setValueRangeEvent.OutputObject
    >;
    setValueRange: TypedContractEvent<
      setValueRangeEvent.InputTuple,
      setValueRangeEvent.OutputTuple,
      setValueRangeEvent.OutputObject
    >;
  };
}
